version: "3"

services:
  server:
    build: srv1/
    command: python ./server.py
    ports:
      - 1234:1234
  
  client:
    build: srv2/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server

